added_functional
YuliaGanchuk/Main-project pull request #13
Opened 2022-06-30 13:09 UTC by YuliaGanchuk

2022-07-01 13:17 UTC, yurakohut requested changes

2022-07-01 13:17 UTC, yurakohut commented on src/pages/home/movie-cards-list.js
> +    console.log(this.props.movies);
видали console.log

2022-07-01 13:17 UTC, yurakohut commented on src/pages/home/tvShows.js
> +      (this.props.numberSelectedPage - 1) * 8,
деструктуризуй this.props

2022-07-01 13:17 UTC, yurakohut commented on src/pages/home/tvShows.js
> +          {filterData.length !== 0 && <Items count={filterData.length} />}
в тебе та сама перевірка
можна об*єднати в одне `<Items count={filterData.length} />` і 
```
<div className={styles.mainCardsBlock} data-element="cardsList">
              <MoviesCards movies={slicePageData}></MoviesCards>
 </div>
```

2022-07-01 19:02 UTC, YuliaGanchuk commented on src/pages/home/movie-cards-list.js
> +    console.log(this.props.movies);
ок

2022-07-01 19:22 UTC, YuliaGanchuk commented on src/pages/home/tvShows.js
> +          {filterData.length !== 0 && <Items count={filterData.length} />}
ок

2022-07-01 19:41 UTC, YuliaGanchuk commented on src/pages/home/tvShows.js
> +      (this.props.numberSelectedPage - 1) * 8,
ніби зробила

2022-07-02 19:49 UTC, yurakohut approved these changes

2022-07-02 20:57 UTC, merged